# Generated by Django 3.1.13 on 2022-07-26 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('assignment_name', models.CharField(max_length=250)),
                ('assignment', models.FileField(upload_to='assignments')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('cover_image', models.ImageField(default='equesttechnicallms/static/img/brand/favicon.png', upload_to='courses/cover_images/')),
                ('logo', models.ImageField(default='equesttechnicallms/static/img/brand/favicon.png', upload_to='courses/logo/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.coursecategories')),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Instructors', serialize=False, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('joined', models.DateField(auto_created=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Student', serialize=False, to='users.user')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
            options={
                'ordering': ['-joined'],
            },
        ),
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('submit', models.FileField(upload_to='Submission')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_submit', to='base.instructors')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submit', to='base.student')),
                ('submitted_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_for_assignment', to='base.classassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentsInClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to='base.instructors')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_student_name', to='base.student')),
            ],
            options={
                'unique_together': {('instructor', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField()),
                ('maximum_marks', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.courses')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_marks', to='base.instructors')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='base.student')),
            ],
        ),
        migrations.AddField(
            model_name='instructors',
            name='class_students',
            field=models.ManyToManyField(through='base.StudentsInClass', to='base.Student'),
        ),
        migrations.AddField(
            model_name='instructors',
            name='course_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='base.coursecategories'),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment', to='base.instructors'),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='student',
            field=models.ManyToManyField(related_name='student_assignment', to='base.Student'),
        ),
        migrations.CreateModel(
            name='MessageToInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('message_html', models.TextField(editable=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base.instructors')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='base.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'message')},
            },
        ),
        migrations.CreateModel(
            name='ClassNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('message_html', models.TextField(editable=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='base.instructors')),
                ('students', models.ManyToManyField(related_name='class_notice', to='base.Student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('instructor', 'message')},
            },
        ),
    ]
